# Changes here will be overwritten by Copier
_commit: 0.2.5
_src_path: https://github.com/aviation-impact-accelerator/aia-template-python
aia_private_package_registry: true
camia_engine: runtime
camia_model: runtime
camia_report: true
docs: true
docs_base: aia-model-contrial-avoidance
mkdocs_prebuild: true
package_mode: true
project_description: Engine for modelling navigational contrail avoidance
project_name: AIA Model Contrial Avoidance
python_package_distribution_name: aia-model-contrial-avoidance
python_package_import_name: aia_model_contrial_avoidance
repository_name: aia-model-contrial-avoidance
repository_url: https://github.com/s-ana-314/aia-model-contrial-avoidance
